import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.signIn': 'Sign In',
    'header.aquasense': 'AquaSense',
    'header.dashboard': 'AquaSense Dashboard',
    'header.farmControl': 'Farm Irrigation Control Center',
    'header.online': 'Online',
    'header.offline': 'Offline',
    'header.logout': 'Logout',
    
    // Landing Page
    'landing.hero.title': "Smart Irrigation for Morocco's Future",
    'landing.hero.subtitle': 'Combat water scarcity with IoT-powered precision agriculture. Save up to 60% water while improving crop yields through real-time soil monitoring and automated irrigation control.',
    'landing.hero.cta': 'Get Started',
    'landing.challenge.title': 'The Water Challenge in Morocco',
    'landing.challenge.subtitle': 'Morocco faces severe water stress with agriculture consuming 85% of available water resources. Traditional irrigation methods waste precious water through inefficient scheduling and lack of real-time data.',
    'landing.challenge.scarcity.title': 'Water Scarcity',
    'landing.challenge.scarcity.text': 'Limited water availability threatens agricultural productivity and food security',
    'landing.challenge.timing.title': 'Inefficient Timing',
    'landing.challenge.timing.text': "Manual irrigation schedules don't adapt to real soil moisture conditions",
    'landing.challenge.waste.title': 'Water Waste',
    'landing.challenge.waste.text': 'Over-irrigation leads to water loss, soil degradation, and increased costs',
    'landing.features.title': 'Intelligent Features',
    'landing.features.subtitle': 'Advanced IoT sensors and automation for precision agriculture',
    'landing.features.monitoring.title': 'Real-Time Soil Monitoring',
    'landing.features.monitoring.text': 'Continuous soil moisture tracking with high-precision capacitive sensors. Get instant readings (0-100%) to understand exact soil water content and plant hydration levels.',
    'landing.features.irrigation.title': 'Automated Irrigation Control',
    'landing.features.irrigation.text': 'Smart relay-controlled water pumps activate automatically based on soil moisture thresholds. Manual override available through secure dashboard for emergency control.',
    'landing.features.weather.title': 'Weather Integration (DHT Sensors)',
    'landing.features.weather.text': 'Track air temperature and humidity in real-time. Correlate environmental conditions with irrigation needs for smarter water management decisions.',
    'landing.features.analytics.title': 'Data Analytics & Insights',
    'landing.features.analytics.text': '24-hour trend charts and daily water consumption statistics. Identify patterns, optimize irrigation schedules, and track water savings over time.',
    'landing.benefits.title': 'Proven Benefits',
    'landing.benefits.subtitle': 'Transform your farm with data-driven irrigation',
    'landing.benefits.water.title': '60% Water Savings',
    'landing.benefits.water.text': 'Reduce water consumption dramatically by irrigating only when soil moisture drops below optimal levels. Eliminate waste from over-irrigation.',
    'landing.benefits.plants.title': 'Healthier Plants',
    'landing.benefits.plants.text': 'Maintain ideal soil moisture for optimal root development and nutrient uptake. Prevent stress from drought or waterlogging.',
    'landing.benefits.costs.title': 'Lower Operating Costs',
    'landing.benefits.costs.text': 'Save on water bills, reduce labor costs with automation, and increase yields. Typical ROI achieved within first growing season.',
    'landing.cta.title': 'Ready to Transform Your Farm?',
    'landing.cta.subtitle': 'Join Moroccan farmers who are saving water, reducing costs, and growing healthier crops with AquaSense.',
    'landing.cta.button': 'Get Started Today',
    'landing.footer.copyright': '© 2026 AquaSense. Smart Irrigation for Sustainable Agriculture.',
    
    // Login Page
    'login.title': 'AquaSense',
    'login.subtitle': 'Farmer Portal',
    'login.welcome': 'Welcome Back',
    'login.instruction': 'Sign in to access your irrigation dashboard',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'farmer@example.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.demo': 'Demo:',
    'login.demoText': 'Use any email/password to access',
    'login.backHome': '← Back to Home',
    
    // Dashboard
    'dashboard.airTemp': 'Air Temperature',
    'dashboard.airHumidity': 'Air Humidity',
    'dashboard.todayDate': "Today's Date",
    'dashboard.systemTime': 'System Time:',
    'dashboard.dhtReading': 'DHT Sensor Reading',
    'dashboard.soilMoisture': 'Real-Time Soil Moisture',
    'dashboard.moistureLevel': 'Moisture Level',
    'dashboard.dry': 'Dry - Irrigation Needed',
    'dashboard.moderate': 'Moderate - Monitor',
    'dashboard.optimal': 'Optimal',
    'dashboard.soilSensor': 'Capacitive Soil Sensor - Field Zone A',
    'dashboard.pumpControl': 'Water Pump Control',
    'dashboard.pumpActive': 'PUMP ACTIVE',
    'dashboard.pumpOff': 'PUMP OFF',
    'dashboard.pumpActiveText': 'Water is being delivered to the field',
    'dashboard.pumpOffText': 'No irrigation in progress',
    'dashboard.stopPump': 'STOP PUMP',
    'dashboard.startPump': 'START PUMP',
    'dashboard.manualOverride': 'Manual Override Control',
    'dashboard.moistureTrend': '24-Hour Soil Moisture Trend',
    'dashboard.moistureLabel': 'Moisture (%)',
    'dashboard.historicalData': 'Historical data from capacitive soil sensor',
    'dashboard.waterConsumption': 'Weekly Water Consumption',
    'dashboard.litersLabel': 'Liters',
    'dashboard.totalWeek': 'Total this week:',
    'dashboard.liters': 'liters',
    'dashboard.avgMoisture': 'Average Moisture (24h)',
    'dashboard.waterSaved': 'Water Saved vs Traditional',
    'dashboard.uptime': 'System Uptime',
    'dashboard.sensorHealth': 'Sensor Health',
    'dashboard.excellent': 'Excellent',
  },
  fr: {
    // Header
    'header.signIn': 'Se Connecter',
    'header.aquasense': 'AquaSense',
    'header.dashboard': 'Tableau de Bord AquaSense',
    'header.farmControl': "Centre de Contrôle d'Irrigation de la Ferme",
    'header.online': 'En Ligne',
    'header.offline': 'Hors Ligne',
    'header.logout': 'Déconnexion',
    
    // Landing Page
    'landing.hero.title': "Irrigation Intelligente pour l'Avenir du Maroc",
    'landing.hero.subtitle': "Combattez la pénurie d'eau avec l'agriculture de précision IoT. Économisez jusqu'à 60% d'eau tout en améliorant les rendements grâce à la surveillance en temps réel de l'humidité du sol et au contrôle automatisé de l'irrigation.",
    'landing.hero.cta': 'Commencer',
    'landing.challenge.title': "Le Défi de l'Eau au Maroc",
    'landing.challenge.subtitle': "Le Maroc fait face à un stress hydrique sévère, l'agriculture consommant 85% des ressources en eau disponibles. Les méthodes d'irrigation traditionnelles gaspillent l'eau précieuse en raison d'une planification inefficace et d'un manque de données en temps réel.",
    'landing.challenge.scarcity.title': "Pénurie d'Eau",
    'landing.challenge.scarcity.text': 'La disponibilité limitée en eau menace la productivité agricole et la sécurité alimentaire',
    'landing.challenge.timing.title': 'Planification Inefficace',
    'landing.challenge.timing.text': "Les programmes d'irrigation manuels ne s'adaptent pas aux conditions réelles d'humidité du sol",
    'landing.challenge.waste.title': "Gaspillage d'Eau",
    'landing.challenge.waste.text': "La sur-irrigation entraîne des pertes d'eau, la dégradation des sols et une augmentation des coûts",
    'landing.features.title': 'Fonctionnalités Intelligentes',
    'landing.features.subtitle': "Capteurs IoT avancés et automatisation pour l'agriculture de précision",
    'landing.features.monitoring.title': 'Surveillance du Sol en Temps Réel',
    'landing.features.monitoring.text': "Suivi continu de l'humidité du sol avec des capteurs capacitifs de haute précision. Obtenez des lectures instantanées (0-100%) pour comprendre la teneur exacte en eau du sol et les niveaux d'hydratation des plantes.",
    'landing.features.irrigation.title': "Contrôle d'Irrigation Automatisé",
    'landing.features.irrigation.text': "Les pompes à eau contrôlées par relais intelligent s'activent automatiquement en fonction des seuils d'humidité du sol. Contrôle manuel disponible via un tableau de bord sécurisé pour le contrôle d'urgence.",
    'landing.features.weather.title': 'Intégration Météo (Capteurs DHT)',
    'landing.features.weather.text': "Suivez la température et l'humidité de l'air en temps réel. Corrélez les conditions environnementales avec les besoins d'irrigation pour des décisions de gestion de l'eau plus intelligentes.",
    'landing.features.analytics.title': 'Analyses et Informations',
    'landing.features.analytics.text': "Graphiques de tendances sur 24 heures et statistiques de consommation d'eau quotidienne. Identifiez les modèles, optimisez les calendriers d'irrigation et suivez les économies d'eau au fil du temps.",
    'landing.benefits.title': 'Avantages Prouvés',
    'landing.benefits.subtitle': 'Transformez votre ferme avec une irrigation basée sur les données',
    'landing.benefits.water.title': "60% d'Économie d'Eau",
    'landing.benefits.water.text': "Réduisez considérablement la consommation d'eau en irriguant uniquement lorsque l'humidité du sol descend en dessous des niveaux optimaux. Éliminez le gaspillage dû à la sur-irrigation.",
    'landing.benefits.plants.title': 'Plantes Plus Saines',
    'landing.benefits.plants.text': "Maintenez une humidité optimale du sol pour un développement racinaire optimal et une absorption des nutriments. Prévenez le stress dû à la sécheresse ou à l'engorgement.",
    'landing.benefits.costs.title': "Coûts d'Exploitation Réduits",
    'landing.benefits.costs.text': "Économisez sur les factures d'eau, réduisez les coûts de main-d'œuvre grâce à l'automatisation et augmentez les rendements. ROI typique atteint dès la première saison de croissance.",
    'landing.cta.title': 'Prêt à Transformer Votre Ferme?',
    'landing.cta.subtitle': "Rejoignez les agriculteurs marocains qui économisent l'eau, réduisent les coûts et cultivent des cultures plus saines avec AquaSense.",
    'landing.cta.button': "Commencer Aujourd'hui",
    'landing.footer.copyright': '© 2026 AquaSense. Irrigation Intelligente pour une Agriculture Durable.',
    
    // Login Page
    'login.title': 'AquaSense',
    'login.subtitle': 'Portail Agriculteur',
    'login.welcome': 'Bon Retour',
    'login.instruction': "Connectez-vous pour accéder à votre tableau de bord d'irrigation",
    'login.email': 'Adresse Email',
    'login.emailPlaceholder': 'agriculteur@exemple.com',
    'login.password': 'Mot de Passe',
    'login.passwordPlaceholder': 'Entrez votre mot de passe',
    'login.remember': 'Se souvenir de moi',
    'login.forgot': 'Mot de passe oublié?',
    'login.signIn': 'Se Connecter',
    'login.demo': 'Démo:',
    'login.demoText': "Utilisez n'importe quel email/mot de passe pour accéder",
    'login.backHome': "← Retour à l'Accueil",
    
    // Dashboard
    'dashboard.airTemp': "Température de l'Air",
    'dashboard.airHumidity': "Humidité de l'Air",
    'dashboard.todayDate': "Date d'Aujourd'hui",
    'dashboard.systemTime': 'Heure du Système:',
    'dashboard.dhtReading': 'Lecture Capteur DHT',
    'dashboard.soilMoisture': 'Humidité du Sol en Temps Réel',
    'dashboard.moistureLevel': "Niveau d'Humidité",
    'dashboard.dry': 'Sec - Irrigation Nécessaire',
    'dashboard.moderate': 'Modéré - Surveiller',
    'dashboard.optimal': 'Optimal',
    'dashboard.soilSensor': 'Capteur de Sol Capacitif - Zone A',
    'dashboard.pumpControl': "Contrôle de la Pompe à Eau",
    'dashboard.pumpActive': 'POMPE ACTIVE',
    'dashboard.pumpOff': 'POMPE ARRÊTÉE',
    'dashboard.pumpActiveText': "L'eau est distribuée au champ",
    'dashboard.pumpOffText': "Aucune irrigation en cours",
    'dashboard.stopPump': 'ARRÊTER LA POMPE',
    'dashboard.startPump': 'DÉMARRER LA POMPE',
    'dashboard.manualOverride': 'Contrôle Manuel',
    'dashboard.moistureTrend': "Tendance d'Humidité du Sol sur 24h",
    'dashboard.moistureLabel': 'Humidité (%)',
    'dashboard.historicalData': 'Données historiques du capteur de sol capacitif',
    'dashboard.waterConsumption': "Consommation d'Eau Hebdomadaire",
    'dashboard.litersLabel': 'Litres',
    'dashboard.totalWeek': 'Total cette semaine:',
    'dashboard.liters': 'litres',
    'dashboard.avgMoisture': 'Humidité Moyenne (24h)',
    'dashboard.waterSaved': "Eau Économisée vs Traditionnel",
    'dashboard.uptime': 'Disponibilité du Système',
    'dashboard.sensorHealth': 'État du Capteur',
    'dashboard.excellent': 'Excellent',
  },
  ar: {
    // Header
    'header.signIn': 'تسجيل الدخول',
    'header.aquasense': 'أكواسينس',
    'header.dashboard': 'لوحة تحكم أكواسينس',
    'header.farmControl': 'مركز التحكم في الري الزراعي',
    'header.online': 'متصل',
    'header.offline': 'غير متصل',
    'header.logout': 'تسجيل الخروج',
    
    // Landing Page
    'landing.hero.title': 'الري الذكي لمستقبل المغرب',
    'landing.hero.subtitle': 'كافح ندرة المياه بالزراعة الدقيقة المدعومة بإنترنت الأشياء. وفر حتى 60٪ من المياه مع تحسين المحاصيل من خلال مراقبة رطوبة التربة في الوقت الفعلي والتحكم الآلي في الري.',
    'landing.hero.cta': 'ابدأ الآن',
    'landing.challenge.title': 'تحدي المياه في المغرب',
    'landing.challenge.subtitle': 'يواجه المغرب إجهاداً مائياً شديداً حيث تستهلك الزراعة 85٪ من موارد المياه المتاحة. تهدر طرق الري التقليدية المياه الثمينة من خلال الجدولة غير الفعالة ونقص البيانات في الوقت الفعلي.',
    'landing.challenge.scarcity.title': 'ندرة المياه',
    'landing.challenge.scarcity.text': 'محدودية توافر المياه تهدد الإنتاجية الزراعية والأمن الغذائي',
    'landing.challenge.timing.title': 'توقيت غير فعال',
    'landing.challenge.timing.text': 'جداول الري اليدوية لا تتكيف مع ظروف رطوبة التربة الحقيقية',
    'landing.challenge.waste.title': 'هدر المياه',
    'landing.challenge.waste.text': 'الإفراط في الري يؤدي إلى فقدان المياه وتدهور التربة وزيادة التكاليف',
    'landing.features.title': 'ميزات ذكية',
    'landing.features.subtitle': 'أجهزة استشعار متقدمة وأتمتة للزراعة الدقيقة',
    'landing.features.monitoring.title': 'مراقبة التربة في الوقت الفعلي',
    'landing.features.monitoring.text': 'تتبع مستمر لرطوبة التربة بأجهزة استشعار سعوية عالية الدقة. احصل على قراءات فورية (0-100٪) لفهم محتوى الماء الدقيق في التربة ومستويات ترطيب النباتات.',
    'landing.features.irrigation.title': 'التحكم الآلي في الري',
    'landing.features.irrigation.text': 'مضخات المياه المتحكم بها عبر المرحلات الذكية تنشط تلقائياً بناءً على عتبات رطوبة التربة. التحكم اليدوي متاح عبر لوحة التحكم الآمنة للتحكم في حالات الطوارئ.',
    'landing.features.weather.title': 'التكامل مع الطقس (مستشعرات DHT)',
    'landing.features.weather.text': 'تتبع درجة حرارة الهواء والرطوبة في الوقت الفعلي. ربط الظروف البيئية باحتياجات الري لاتخاذ قرارات أذكى في إدارة المياه.',
    'landing.features.analytics.title': 'تحليل البيانات والرؤى',
    'landing.features.analytics.text': 'مخططات الاتجاه على مدار 24 ساعة وإحصائيات استهلاك المياه اليومية. حدد الأنماط، وحسّن جداول الري، وتتبع توفير المياه بمرور الوقت.',
    'landing.benefits.title': 'فوائد مثبتة',
    'landing.benefits.subtitle': 'حول مزرعتك بالري القائم على البيانات',
    'landing.benefits.water.title': '60٪ توفير في المياه',
    'landing.benefits.water.text': 'قلل استهلاك المياه بشكل كبير من خلال الري فقط عندما تنخفض رطوبة التربة عن المستويات المثلى. القضاء على الهدر من الإفراط في الري.',
    'landing.benefits.plants.title': 'نباتات أكثر صحة',
    'landing.benefits.plants.text': 'حافظ على رطوبة التربة المثالية لنمو الجذور الأمثل وامتصاص العناصر الغذائية. منع الإجهاد من الجفاف أو التشبع بالماء.',
    'landing.benefits.costs.title': 'تكاليف تشغيل أقل',
    'landing.benefits.costs.text': 'وفر في فواتير المياه، قلل تكاليف العمالة بالأتمتة، وزد الإنتاجية. عائد الاستثمار النموذجي يتحقق في موسم النمو الأول.',
    'landing.cta.title': 'هل أنت مستعد لتحويل مزرعتك؟',
    'landing.cta.subtitle': 'انضم إلى المزارعين المغاربة الذين يوفرون المياه ويخفضون التكاليف ويزرعون محاصيل أكثر صحة مع أكواسينس.',
    'landing.cta.button': 'ابدأ اليوم',
    'landing.footer.copyright': '© 2026 أكواسينس. الري الذكي للزراعة المستدامة.',
    
    // Login Page
    'login.title': 'أكواسينس',
    'login.subtitle': 'بوابة المزارع',
    'login.welcome': 'مرحباً بعودتك',
    'login.instruction': 'سجل الدخول للوصول إلى لوحة تحكم الري',
    'login.email': 'عنوان البريد الإلكتروني',
    'login.emailPlaceholder': 'farmer@example.com',
    'login.password': 'كلمة المرور',
    'login.passwordPlaceholder': 'أدخل كلمة المرور',
    'login.remember': 'تذكرني',
    'login.forgot': 'نسيت كلمة المرور؟',
    'login.signIn': 'تسجيل الدخول',
    'login.demo': 'تجريبي:',
    'login.demoText': 'استخدم أي بريد إلكتروني/كلمة مرور للوصول',
    'login.backHome': '← العودة للرئيسية',
    
    // Dashboard
    'dashboard.airTemp': 'درجة حرارة الهواء',
    'dashboard.airHumidity': 'رطوبة الهواء',
    'dashboard.todayDate': 'تاريخ اليوم',
    'dashboard.systemTime': 'وقت النظام:',
    'dashboard.dhtReading': 'قراءة مستشعر DHT',
    'dashboard.soilMoisture': 'رطوبة التربة في الوقت الفعلي',
    'dashboard.moistureLevel': 'مستوى الرطوبة',
    'dashboard.dry': 'جاف - الري مطلوب',
    'dashboard.moderate': 'معتدل - مراقبة',
    'dashboard.optimal': 'مثالي',
    'dashboard.soilSensor': 'مستشعر التربة السعوي - المنطقة أ',
    'dashboard.pumpControl': 'التحكم في مضخة المياه',
    'dashboard.pumpActive': 'المضخة نشطة',
    'dashboard.pumpOff': 'المضخة متوقفة',
    'dashboard.pumpActiveText': 'يتم توصيل المياه إلى الحقل',
    'dashboard.pumpOffText': 'لا يوجد ري جاري',
    'dashboard.stopPump': 'إيقاف المضخة',
    'dashboard.startPump': 'تشغيل المضخة',
    'dashboard.manualOverride': 'التحكم اليدوي',
    'dashboard.moistureTrend': 'اتجاه رطوبة التربة على مدار 24 ساعة',
    'dashboard.moistureLabel': 'الرطوبة (%)',
    'dashboard.historicalData': 'البيانات التاريخية من مستشعر التربة السعوي',
    'dashboard.waterConsumption': 'استهلاك المياه الأسبوعي',
    'dashboard.litersLabel': 'لتر',
    'dashboard.totalWeek': 'الإجمالي هذا الأسبوع:',
    'dashboard.liters': 'لتر',
    'dashboard.avgMoisture': 'متوسط الرطوبة (24 ساعة)',
    'dashboard.waterSaved': 'المياه الموفرة مقابل التقليدي',
    'dashboard.uptime': 'وقت تشغيل النظام',
    'dashboard.sensorHealth': 'حالة المستشعر',
    'dashboard.excellent': 'ممتاز',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
